sudo: required
dist: trusty
language: node_js
node_js:
  - '9'
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm test
before_script:
  - sh scripts/rpc.sh &
  - sleep 5
